version: "3"
services:
  api:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.api
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY:-root}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY:-password}
      - MINIO_URL=minio:9000
    networks:
      - sdnet
    depends_on:
      - redis
      - minio
    restart: always

  worker:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.worker
    environment:
      - REDIS_URL=redis://redis:6379/0
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY:-root}
      - MINIO_SECRET_KEY=${MINIO_ACCESS_KEY:-password}
      - MINIO_URL=minio:9000
    networks:
      - sdnet
    depends_on:
      - redis
      - minio
    restart: always
    volumes:
      - ai_model_data:/root/.cache/huggingface/hub
      - gfpgan_data:/app/gfpgan
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "root"
      MINIO_ROOT_PASSWORD: "password"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - sdnet

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - sdnet
    restart: always

volumes:
  minio_data:
  ai_model_data:
  gfpgan_data:

networks:
  sdnet:
